### ISSUE TITLE
box-sizing: border box

### ISSUE THREAD

**Issue by dbox** [misega/HTML5-Banners#4]
Is there any reason for having the `width: calc($width -2px)` vs adding `box-sizing: border-box`:

``` scss
*, *:before, *:after {
  box-sizing: border-box;
}


#ad {
    width: $width;
    height: $height;
}
```
